In [4]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics

iris=load_iris()
x=iris.data
y=iris.target

print("Data : " + str(x[:5]), "Target : " + str(y[:5]),sep="\n")

xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.4,random_state=1)

print("Shape : " + str(iris.data.shape))
print(len(xtrain))
print(len(ytest))

knn=KNeighborsClassifier(n_neighbors=1)
knn.fit(xtrain,ytrain)
pred=knn.predict(xtest)

print("Accuracy",metrics.accuracy_score(ytest,pred))
print(iris.target_names[2])

ytestn=[iris.target_names[i] for i in ytest]
predn=[iris.target_names[i] for i in pred]

print(" predicted Actual")
for i in range(len(pred)):
 print(i," ",predn[i]," ",ytestn[i])

Data[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
Target[0 0 0 0 0]
(150, 4)
90
60
Accuracy 0.9666666666666667
virginica
 predicted Actual
0   setosa   setosa
1   versicolor   versicolor
2   versicolor   versicolor
3   setosa   setosa
4   virginica   virginica
5   virginica   versicolor
6   virginica   virginica
7   setosa   setosa
8   setosa   setosa
9   virginica   virginica
10   versicolor   versicolor
11   setosa   setosa
12   virginica   virginica
13   versicolor   versicolor
14   versicolor   versicolor
15   setosa   setosa
16   versicolor   versicolor
17   versicolor   versicolor
18   setosa   setosa
19   setosa   setosa
20   versicolor   versicolor
21   versicolor   versicolor
22   versicolor   versicolor
23   setosa   setosa
24   virginica   virginica
25   versicolor   versicolor
26   setosa   setosa
27   setosa   setosa
28   versicolor   versicolor
29   virginica   virginica
30   versicolor   versicolor
31   virginica   virgin