In [54]:
import numpy as np

# X = (hours studying, hours sleeping), y = score on test, xPredicted = 4 hours studying & 8 hours sleeping (input data for prediction)
X = np.array(([2, 9], [1, 5], [3, 6]), dtype=float)
y = np.array(([92], [86], [89]), dtype=float)
xPredicted = np.array(([4,8]), dtype=float)

# scale units
X = X/np.amax(X, axis=0) # maximum of X array
xPredicted = xPredicted/np.amax(xPredicted, axis=0) # maximum of xPredicted (our input data for the prediction)
y = y/100 # max test score is 100


class Neural_Network(object):
    def __init__(self):
        self.inputSize = 2
        self.outputSize = 1
        self.hiddenSize = 3
        self.W1 = np.random.randn(self.inputSize, self.hiddenSize) # (3x2) weight matrix from input to hidden layer
        self.W2 = np.random.randn(self.hiddenSize, self.outputSize) # (3x1) weight matrix from hidden to output layer

    def forward(self, X):
        self.z = np.dot(X, self.W1) # dot product of X (input) and first set of 3x2 weights
        self.z2 = self.sigmoid(self.z) # activation function
        self.z3 = np.dot(self.z2, self.W2) # dot product of hidden layer (z2) and second set of 3x1 weights
        o = self.sigmoid(self.z3) # final activation function
        return o

    def sigmoid(self, s):  
        return 1/(1+np.exp(-s))

    def sigmoidPrime(self, s):
        return s * (1 - s)
    
    def backward(self, X, y, o):
        self.o_error = y - o # error in output
        self.o_delta = self.o_error*self.sigmoidPrime(o) # applying derivative of sigmoid to error

        self.z2_error = self.o_delta.dot(self.W2.T) # z2 error: how much our hidden layer weights contributed to output error
        self.z2_delta = self.z2_error*self.sigmoidPrime(self.z2) # applying derivative of sigmoid to z2 error

        self.W1 += X.T.dot(self.z2_delta) # adjusting first set (input --> hidden) weights
        self.W2 += self.z2.T.dot(self.o_delta) # adjusting second set (hidden --> output) weights

    def train(self, X, y):
        o = self.forward(X)
        self.backward(X, y, o)
    
    def saveWeights(self):
        np.savetxt("w1.txt", self.W1, fmt="%s")
        np.savetxt("w2.txt", self.W2, fmt="%s")

    def predict(self):
        print("Predicted data based on trained weights: ")
        print("Input (scaled): \n" + str(xPredicted))
        print("Output: \n" + str(self.forward(xPredicted)))

NN = Neural_Network()
for i in range(1000): # trains the NN 1,000 times
    print("# " + str(i) + "\n")
    print("Input (scaled): \n" + str(X))
    print("Actual Output: \n" + str(y))
    print("Predicted Output: \n" + str(NN.forward(X)))
    print("Loss: \n" + str(np.mean(np.square(y - NN.forward(X))))) # mean sum squared loss
    print("\n")
    
    NN.train(X, y)
    NN.saveWeights()
    NN.predict()


# 0

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.44909988]
 [0.44456098]
 [0.43386175]]
Loss: 
0.20079953525004088


Predicted data based on trained weights: 
Input (scaled): 
[0.5 1. ]
Output: 
[0.56980005]
# 1

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.56949271]
 [0.54997374]
 [0.55345061]]
Loss: 
0.11074571284833307


Predicted data based on trained weights: 
Input (scaled): 
[0.5 1. ]
Output: 
[0.65151386]
# 2

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.65352181]
 [0.6252824 ]
 [0.63795767]]
Loss: 
0.06320943874531101


Predicted data based on trained weights: 
Input (scaled): 
[0.5 1. ]
Output: 
[0.70457295]
# 3

Input (scaled): 
[[0.66666667 1.

Loss: 
0.00024355686176868877


Predicted data based on trained weights: 
Input (scaled): 
[0.5 1. ]
Output: 
[0.88928374]
# 42

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.8939091 ]
 [0.86130807]
 [0.88545873]]
Loss: 
0.00023435636538898533


Predicted data based on trained weights: 
Input (scaled): 
[0.5 1. ]
Output: 
[0.88972208]
# 43

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89434138]
 [0.86178335]
 [0.88591029]]
Loss: 
0.0002260903375836216


Predicted data based on trained weights: 
Input (scaled): 
[0.5 1. ]
Output: 
[0.8901365]
# 44

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89474995]
 [0.8622328 ]
 [0.88633686]]
Loss: 
0.000218656293441770

 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90096968]
 [0.86908671]
 [0.8927532 ]]
Loss: 
0.0001507671220196257


Predicted data based on trained weights: 
Input (scaled): 
[0.5 1. ]
Output: 
[0.89655043]
# 77

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.9010495 ]
 [0.86917425]
 [0.89283264]]
Loss: 
0.00015043741313655186


Predicted data based on trained weights: 
Input (scaled): 
[0.5 1. ]
Output: 
[0.89662877]
# 78

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90112577]
 [0.86925785]
 [0.89290835]]
Loss: 
0.00015013421175838658


Predicted data based on trained weights: 
Input (scaled): 
[0.5 1. ]
Output: 
[0.89670371]
# 79

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]


Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90234974]
 [0.87058145]
 [0.89405791]]
Loss: 
0.00014665517697411663


Predicted data based on trained weights: 
Input (scaled): 
[0.5 1. ]
Output: 
[0.89792162]
# 108

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90237078]
 [0.87060349]
 [0.89407516]]
Loss: 
0.0001466100204978842


Predicted data based on trained weights: 
Input (scaled): 
[0.5 1. ]
Output: 
[0.89794313]
# 109

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.902391  ]
 [0.87062459]
 [0.89409152]]
Loss: 
0.00014656646429210893


Predicted data based on trained weights: 
Input (scaled): 
[0.5 1. ]
Output: 
[0.89796384]
# 110

Input (scaled): 
[[0.66

Predicted data based on trained weights: 
Input (scaled): 
[0.5 1. ]
Output: 
[0.89840134]
# 149

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90280336]
 [0.87102605]
 [0.89432755]]
Loss: 
0.0001453420038984806


Predicted data based on trained weights: 
Input (scaled): 
[0.5 1. ]
Output: 
[0.89840732]
# 150

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90280828]
 [0.87103006]
 [0.89432779]]
Loss: 
0.00014531578711712712


Predicted data based on trained weights: 
Input (scaled): 
[0.5 1. ]
Output: 
[0.89841317]
# 151

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90281307]
 [0.87103394]
 [0.89432788]]
Loss: 
0.0001452896275905419


Predicted data based on 

[0.5 1. ]
Output: 
[0.89858038]
# 190

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90294041]
 [0.87111855]
 [0.89427034]]
Loss: 
0.00014429588542600805


Predicted data based on trained weights: 
Input (scaled): 
[0.5 1. ]
Output: 
[0.89858379]
# 191

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90294282]
 [0.87111977]
 [0.89426801]]
Loss: 
0.00014427087536339413


Predicted data based on trained weights: 
Input (scaled): 
[0.5 1. ]
Output: 
[0.89858717]
# 192

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90294521]
 [0.87112097]
 [0.89426566]]
Loss: 
0.0001442458846270338


Predicted data based on trained weights: 
Input (scaled): 
[0.5 1. ]
Output: 
[0.8

 [0.89414065]]
Loss: 
0.00014306788818420883


Predicted data based on trained weights: 
Input (scaled): 
[0.5 1. ]
Output: 
[0.89873743]
# 241

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90304764]
 [0.87116362]
 [0.89413794]]
Loss: 
0.00014304378161007414


Predicted data based on trained weights: 
Input (scaled): 
[0.5 1. ]
Output: 
[0.89874032]
# 242

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90304958]
 [0.87116432]
 [0.89413524]]
Loss: 
0.00014301969239352105


Predicted data based on trained weights: 
Input (scaled): 
[0.5 1. ]
Output: 
[0.89874321]
# 243

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90305151]
 [0.87116503]
 [0.89413253]]
Loss: 


Predicted data based on trained weights: 
Input (scaled): 
[0.5 1. ]
Output: 
[0.89881163]
# 267

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90309718]
 [0.87118119]
 [0.89406753]]
Loss: 
0.00014242304671864593


Predicted data based on trained weights: 
Input (scaled): 
[0.5 1. ]
Output: 
[0.89881445]
# 268

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90309906]
 [0.87118184]
 [0.89406483]]
Loss: 
0.00014239940207128068


Predicted data based on trained weights: 
Input (scaled): 
[0.5 1. ]
Output: 
[0.89881727]
# 269

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90310094]
 [0.87118249]
 [0.89406213]]
Loss: 
0.00014237577427047776


Predicted data based o

Predicted data based on trained weights: 
Input (scaled): 
[0.5 1. ]
Output: 
[0.89890366]
# 300

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90315854]
 [0.87120212]
 [0.89397898]]
Loss: 
0.00014165156917501275


Predicted data based on trained weights: 
Input (scaled): 
[0.5 1. ]
Output: 
[0.89890642]
# 301

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90316038]
 [0.87120274]
 [0.89397632]]
Loss: 
0.00014162847089992635


Predicted data based on trained weights: 
Input (scaled): 
[0.5 1. ]
Output: 
[0.89890918]
# 302

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90316222]
 [0.87120336]
 [0.89397366]]
Loss: 
0.00014160538887754635


Predicted data based o

Predicted data based on trained weights: 
Input (scaled): 
[0.5 1. ]
Output: 
[0.89901285]
# 340

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90323149]
 [0.87122638]
 [0.89387374]]
Loss: 
0.00014074014252036266


Predicted data based on trained weights: 
Input (scaled): 
[0.5 1. ]
Output: 
[0.89901555]
# 341

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90323329]
 [0.87122697]
 [0.89387114]]
Loss: 
0.00014071768076312117


Predicted data based on trained weights: 
Input (scaled): 
[0.5 1. ]
Output: 
[0.89901825]
# 342

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.9032351 ]
 [0.87122756]
 [0.89386854]]
Loss: 
0.00014069523456661348


Predicted data based o

Predicted data based on trained weights: 
Input (scaled): 
[0.5 1. ]
Output: 
[0.89911181]
# 377

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90329781]
 [0.87124798]
 [0.89377861]]
Loss: 
0.00013991929057049842


Predicted data based on trained weights: 
Input (scaled): 
[0.5 1. ]
Output: 
[0.89911446]
# 378

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90329959]
 [0.87124855]
 [0.89377606]]
Loss: 
0.00013989739342203813


Predicted data based on trained weights: 
Input (scaled): 
[0.5 1. ]
Output: 
[0.89911711]
# 379

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90330137]
 [0.87124912]
 [0.89377353]]
Loss: 
0.0001398755112196216


Predicted data based on

 [0.89367816]]
Loss: 
0.00013905490323323536


Predicted data based on trained weights: 
Input (scaled): 
[0.5 1. ]
Output: 
[0.89921927]
# 418

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90337009]
 [0.87127104]
 [0.89367568]]
Loss: 
0.00013903359139446776


Predicted data based on trained weights: 
Input (scaled): 
[0.5 1. ]
Output: 
[0.89922186]
# 419

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90337184]
 [0.87127159]
 [0.8936732 ]]
Loss: 
0.00013901229386369875


Predicted data based on trained weights: 
Input (scaled): 
[0.5 1. ]
Output: 
[0.89922446]
# 420

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90337358]
 [0.87127214]
 [0.89367073]]
Loss: 


 [0.89359228]]
Loss: 
0.0001383174008521944


Predicted data based on trained weights: 
Input (scaled): 
[0.5 1. ]
Output: 
[0.89930922]
# 453

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.9034308 ]
 [0.87129001]
 [0.89358985]]
Loss: 
0.0001382965806150671


Predicted data based on trained weights: 
Input (scaled): 
[0.5 1. ]
Output: 
[0.89931177]
# 454

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90343252]
 [0.87129054]
 [0.89358743]]
Loss: 
0.00013827577414947032


Predicted data based on trained weights: 
Input (scaled): 
[0.5 1. ]
Output: 
[0.89931432]
# 455

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90343424]
 [0.87129107]
 [0.893585  ]]
Loss: 
0.

Predicted data based on trained weights: 
Input (scaled): 
[0.5 1. ]
Output: 
[0.89939256]
# 486

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90348722]
 [0.87130731]
 [0.89351061]]
Loss: 
0.00013761714938585726


Predicted data based on trained weights: 
Input (scaled): 
[0.5 1. ]
Output: 
[0.89939507]
# 487

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90348892]
 [0.87130782]
 [0.89350824]]
Loss: 
0.00013759678904120423


Predicted data based on trained weights: 
Input (scaled): 
[0.5 1. ]
Output: 
[0.89939757]
# 488

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90349062]
 [0.87130834]
 [0.89350586]]
Loss: 
0.00013757644196579378


Predicted data based o

Predicted data based on trained weights: 
Input (scaled): 
[0.5 1. ]
Output: 
[0.89950884]
# 533

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90356623]
 [0.87133096]
 [0.89340052]]
Loss: 
0.00013667432490377978


Predicted data based on trained weights: 
Input (scaled): 
[0.5 1. ]
Output: 
[0.89951129]
# 534

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.9035679 ]
 [0.87133146]
 [0.89339821]]
Loss: 
0.00013665457279070942


Predicted data based on trained weights: 
Input (scaled): 
[0.5 1. ]
Output: 
[0.89951373]
# 535

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90356956]
 [0.87133195]
 [0.89339591]]
Loss: 
0.00013663483328205139


Predicted data based o

Predicted data based on trained weights: 
Input (scaled): 
[0.5 1. ]
Output: 
[0.89959603]
# 569

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.9036257 ]
 [0.87134832]
 [0.89331834]]
Loss: 
0.0001359710920731041


Predicted data based on trained weights: 
Input (scaled): 
[0.5 1. ]
Output: 
[0.89959842]
# 570

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90362734]
 [0.87134879]
 [0.89331609]]
Loss: 
0.0001359517851409791


Predicted data based on trained weights: 
Input (scaled): 
[0.5 1. ]
Output: 
[0.89960082]
# 571

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90362898]
 [0.87134926]
 [0.89331383]]
Loss: 
0.00013593249032634874


Predicted data based on 

 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90369235]
 [0.87136728]
 [0.89322697]]
Loss: 
0.00013518930433544326


Predicted data based on trained weights: 
Input (scaled): 
[0.5 1. ]
Output: 
[0.89969573]
# 611

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90369396]
 [0.87136773]
 [0.89322477]]
Loss: 
0.0001351704835022495


Predicted data based on trained weights: 
Input (scaled): 
[0.5 1. ]
Output: 
[0.89969807]
# 612

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90369557]
 [0.87136818]
 [0.89322257]]
Loss: 
0.00013515167425467363


Predicted data based on trained weights: 
Input (scaled): 
[0.5 1. ]
Output: 
[0.89970042]
# 613

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667

 [0.89]]
Predicted Output: 
[[0.90375151]
 [0.87138367]
 [0.89314649]]
Loss: 
0.0001345005519243265


Predicted data based on trained weights: 
Input (scaled): 
[0.5 1. ]
Output: 
[0.8997818]
# 648

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.9037531 ]
 [0.8713841 ]
 [0.89314434]]
Loss: 
0.00013448215142156824


Predicted data based on trained weights: 
Input (scaled): 
[0.5 1. ]
Output: 
[0.8997841]
# 649

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90375469]
 [0.87138453]
 [0.8931422 ]]
Loss: 
0.00013446376204441726


Predicted data based on trained weights: 
Input (scaled): 
[0.5 1. ]
Output: 
[0.8997864]
# 650

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output:

Predicted data based on trained weights: 
Input (scaled): 
[0.5 1. ]
Output: 
[0.89989555]
# 698

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90383158]
 [0.87140516]
 [0.89303857]]
Loss: 
0.00013357606114827933


Predicted data based on trained weights: 
Input (scaled): 
[0.5 1. ]
Output: 
[0.8998978]
# 699

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90383314]
 [0.87140556]
 [0.89303649]]
Loss: 
0.00013355821280018674


Predicted data based on trained weights: 
Input (scaled): 
[0.5 1. ]
Output: 
[0.89990004]
# 700

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90383469]
 [0.87140597]
 [0.89303441]]
Loss: 
0.0001335403749733953


Predicted data based on 

Predicted data based on trained weights: 
Input (scaled): 
[0.5 1. ]
Output: 
[0.89997126]
# 732

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90388403]
 [0.87141878]
 [0.89296852]]
Loss: 
0.0001329750514465601


Predicted data based on trained weights: 
Input (scaled): 
[0.5 1. ]
Output: 
[0.89997347]
# 733

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90388556]
 [0.87141917]
 [0.89296648]]
Loss: 
0.00013295755443847807


Predicted data based on trained weights: 
Input (scaled): 
[0.5 1. ]
Output: 
[0.89997568]
# 734

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90388709]
 [0.87141956]
 [0.89296445]]
Loss: 
0.00013294006756724304


Predicted data based on

Predicted data based on trained weights: 
Input (scaled): 
[0.5 1. ]
Output: 
[0.90007163]
# 778

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90395382]
 [0.87143634]
 [0.89287609]]
Loss: 
0.00013218051433441317


Predicted data based on trained weights: 
Input (scaled): 
[0.5 1. ]
Output: 
[0.90007379]
# 779

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90395532]
 [0.87143671]
 [0.89287411]]
Loss: 
0.0001321634723261179


Predicted data based on trained weights: 
Input (scaled): 
[0.5 1. ]
Output: 
[0.90007595]
# 780

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90395682]
 [0.87143708]
 [0.89287213]]
Loss: 
0.00013214643995697456


Predicted data based on

Predicted data based on trained weights: 
Input (scaled): 
[0.5 1. ]
Output: 
[0.90016758]
# 823

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90402083]
 [0.87145255]
 [0.89278821]]
Loss: 
0.00013142301887368848


Predicted data based on trained weights: 
Input (scaled): 
[0.5 1. ]
Output: 
[0.90016969]
# 824

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.9040223 ]
 [0.8714529 ]
 [0.89278629]]
Loss: 
0.00013140640035587783


Predicted data based on trained weights: 
Input (scaled): 
[0.5 1. ]
Output: 
[0.9001718]
# 825

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90402377]
 [0.87145325]
 [0.89278437]]
Loss: 
0.00013138979101428664


Predicted data based on

Predicted data based on trained weights: 
Input (scaled): 
[0.5 1. ]
Output: 
[0.90028602]
# 880

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90410395]
 [0.87147175]
 [0.89268042]]
Loss: 
0.00013049011957424325


Predicted data based on trained weights: 
Input (scaled): 
[0.5 1. ]
Output: 
[0.90028807]
# 881

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90410539]
 [0.87147208]
 [0.89267857]]
Loss: 
0.000130474008419874


Predicted data based on trained weights: 
Input (scaled): 
[0.5 1. ]
Output: 
[0.90029012]
# 882

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90410683]
 [0.8714724 ]
 [0.89267671]]
Loss: 
0.00013045790588766656


Predicted data based on 

Predicted data based on trained weights: 
Input (scaled): 
[0.5 1. ]
Output: 
[0.90037715]
# 925

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90416822]
 [0.87148588]
 [0.89259802]]
Loss: 
0.00012977352160188914


Predicted data based on trained weights: 
Input (scaled): 
[0.5 1. ]
Output: 
[0.90037916]
# 926

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90416963]
 [0.87148619]
 [0.89259622]]
Loss: 
0.0001297577892771636


Predicted data based on trained weights: 
Input (scaled): 
[0.5 1. ]
Output: 
[0.90038116]
# 927

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90417105]
 [0.87148649]
 [0.89259441]]
Loss: 
0.00012974206516144313


Predicted data based on

Predicted data based on trained weights: 
Input (scaled): 
[0.5 1. ]
Output: 
[0.90048383]
# 979

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90424382]
 [0.87150167]
 [0.89250218]]
Loss: 
0.000128935504371348


Predicted data based on trained weights: 
Input (scaled): 
[0.5 1. ]
Output: 
[0.90048578]
# 980

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.9042452 ]
 [0.87150195]
 [0.89250043]]
Loss: 
0.00012892020277536234


Predicted data based on trained weights: 
Input (scaled): 
[0.5 1. ]
Output: 
[0.90048773]
# 981

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90424659]
 [0.87150223]
 [0.89249869]]
Loss: 
0.00012890490891934143


Predicted data based on 